### ISSUE TITLE
Funktionalität Bootstrap 5 Spalten in Formularen?

### ISSUE THREAD

**Issue by vossmedien** [heimrichhannot/contao-subcolumns-bootstrap-bundle#10]
Hallo nochmal,
hatte gerade getestet die Spaltensets im Formular einzusetzen.

Contao 4.13
und deine beiden Subcolumns-Erweiterungen sind im Einsatz

Ich kann zwar das Spaltenset-Element auswählen aber leider nicht das jeweiligen Spaltenset sondern nur die Anzahl an Spalten. Ich kann also weder die Anzahl der Trenn-Elemente, noch das Spaltenset auswählen. Klicke ich auf speichern, werden im Frontend zwar Spalten ausgegeben, aber da kriegt dann die wrapper-row die anzahl der Spalten als Spalte (row col-1) was ja an sich nicht funktioniert und die inneren Spalten haben die selbe Spaltengröße. also auch .row.col-1 > .col-1

Ist hier geplant, die Funktionalität auch hier umzubauen bzw. die Fehler zu beheben?

Danke!

**Comment by davidsky7** [comment]
zusätzlich wird auch noch die ce_form-Div vor dem Formular geschlossen:

<div class="ce_form block"></div>
<form ...

**Comment by koertho** [comment]
@davidsky7 Das mit dem div hat aber nichts mit diesem Bundle hier zu tun.
