### ISSUE TITLE
There is no bootstrap css

### ISSUE THREAD

**Issue by Aybee** [heimrichhannot/contao-subcolumns-bootstrap-bundle#2]
What do we have to do to get the necessary bootstrap css loaded in the front end?

**Comment by koertho** [comment]
This bundle doesn't need any own frontend css, as it uses the bootstrap grid system.

**Comment by Aybee** [comment]
Bootstrap grid css should be a requirement in this extension.

Is there an extension that brings the bootstrap grid css into front end? If so, a hint to this extension would be helpful.

**Comment by koertho** [comment]
No, how you add bootstrap as asset is your choice. There are different ways in contao to do so and no "standardized" way. We're using Symfony Webpack Encore with our [Encore Bundle](https://github.com/heimrichhannot/contao-encore-bundle) for asset management.

**Comment by Aybee** [comment]
Ok, thank you.
