### ISSUE TITLE
Installation aborted in Contao >= 4.7

### ISSUE THREAD

**Issue by syntaxys** [heimrichhannot/contao-subcolumns-bootstrap-bundle#3]
I tried to install that extension in Contao 4.8.3 but there are conflicts with the symfony/framework-bundle[v4.3.4], also in 4.7.7 with symfony/framework-bundle[v4.2.11].

Will it be a big deal to fix that dependencies to the newer symfony/framework-bundle[v4.3.4]?

**Comment by koertho** [comment]
@syntaxys  Thanks for reporting. I removed the framework bundle dependency.

**Comment by daniel-nemeth** [comment]
Hi. Can you pls update packagist. 
The Contao-Manager still requires 1.4.1 of your extension where the symfony framework is still required.

Cheers!

**Comment by koertho** [comment]
@daniel-nemeth Oh, I forgot to create a tag for the fix, sorry! Thanks for reporting!
