### ISSUE TITLE
bootstrap4-Grid - HTML-Ausgabe ohne css bootstrapklassen in den Spalten

### ISSUE THREAD

**Issue by green-pixelbox** [heimrichhannot/contao-subcolumns-bootstrap-bundle#5]
Ersteinmal DANKE für das Modul. Das ist wirklich das best gestaltete Spaltengrid was es für Contao gibt :)
Leider gibt es in der Contao Version 4.8.7 mit diesem Modul in der Version 1.4.3 eine fehlerhafte HTML-Ausgabe. Wenn man in den Einstellungen "bootstrag4" für das Grid ausgewählt hat, fehlen die Klassen in den einzelnen Spalten, damit die Spaltenbreiten von Bootstrap angewendet werden können (siehe Screenshot, dort ist ein 2-Spalter im Einsatz).
![spaltengrid1](https://user-images.githubusercontent.com/3920742/72366479-9f445180-36fa-11ea-89f4-b38d12ca5fc3.JPG)

**Comment by koertho** [comment]
@green-pixelbox Hallo, also ich habe es gerade in einer 4.8 Instanz getestet und keinen Fehler feststellen können. Kann es sein, dass deine Spaltenset-Konfiguration falsch ist? Es sieht so aus, als hättest du keine Größen definiert?

**Comment by green-pixelbox** [comment]
Ich habe das Modul gerade nochmal in eine neue Contao 4.8 installiert. Es funktioniert nun alles. :) Ein super Modul! Danke nochmal dafür.

**Comment by koertho** [comment]
@green-pixelbox Freut mich :)
