### ISSUE TITLE
Fehler bei der Konfiguration der Spaltensets

### ISSUE THREAD

**Issue by contaoacademy** [heimrichhannot/contao-subcolumns-bootstrap-bundle#7]
Ich wollte heute die Erweiterung testen, leider bekomme ich bei der Konfiguration der Spaltensets eine Fehlermeldung:

```
An exception occurred while executing 'UPDATE tl_columnset SET `columnset_xl`='a:3:{i:0;a:3:{s:5:\"width\";s:1:\"4\";s:6:\"offset\";s:0:\"\";s:5:\"order\";s:0:\"\";}i:1;a:3:{s:5:\"width\";s:1:\"4\";s:6:\"offset\";s:0:\"\";s:5:\"order\";s:0:\"\";}i:2;a:3:{s:5:\"width\";s:1:\"4\";s:6:\"offset\";s:0:\"\";s:5:\"order\";s:0:\"\";}}' WHERE id='1'':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'columnset_xl' in 'field list'
```

**Siehe auch Screenshot:**
<img width="1053" alt="screen-20211028_tVRzhMCC" src="https://user-images.githubusercontent.com/23719181/139289003-d29ac301-3c82-4f5e-a1ae-ae07bb515336.png">

**Comment by koertho** [comment]
Hi, ich habe die Readme ergänzt und eine Meldung im Backend eingebaut, welche darauf hinweißt. Mehr kann ich an dieser Stelle nicht tun, wenn ich nicht das ganze Bundle umbauen möchte :D
