### ISSUE TITLE
Fehlende Datenbankspalten bei Bootstrap

### ISSUE THREAD

**Issue by vossmedien** [heimrichhannot/contao-subcolumns-bootstrap-bundle#9]
Hey, 
erst einmal tolle Erweiterung!

Da die Contao-Bootstrap Entwicklung anscheinend nicht mehr weiterentwickelt wird, habe ich deine entdeckt und mich gefreut, da sie genau das machen sollte was ich suche.

Als ich gerade Spaltensets anlegen wollte, bekomme ich jedoch folgende Meldung angezeigt:

Scheinbar wurde nach der Änderungen Subcolumns-Konfiguration die Datenbank noch nicht geupdated. Dies kann zu Fehlern beim Speichern der Konfiguration führen. Bitte updaten Sie die Datenbank, bevor Sie weitermachen.

Speichere ich dennoch, bekomme ich folgende Meldung:

an exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'columnset_lg' in 'field list'

Die Datenbank ist aber aktuell. (Nach dem speichern gab es auch keine Anpassungen zu machen wie in der Readme beschrieben!)

Danke dir fürs checken!

Viele Grüße,

Christian

**Comment by koertho** [comment]
Hi, bitte immer PHP-, Contao- und Bundle-Version mit angeben. Ich kann dir keine schnelle Lösung versprechen. Als workaround könntest du die Spalte vielleicht erstmal selber anlegen.

**Comment by vossmedien** [comment]
Ich schreib das Ticket und mir fällt ne Lösung ein...
Musste nach dem Speichern den Cache leeren, danach war auch das DB Update sichtbar.
Kann dementsprechend geschlossen werden - übernehmts aber vielleicht mal in die Readme :-)

Contao ist auf 4.13.

Danke!
